meta:
    name: 'student_mbv3s_vww96_kd_a'
    seed: 42
    out_dir: 'runs'
    device: 'auto'
    amp: true

data:
    size: 96
    path: 'data/vww96'
    batch: 256
    num_workers: 4
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    aug:
        rand_hflip: 0.5
        color_jitter: [0.2, 0.2, 0.2, 0.0]
        random_erasing: [0.0, 0.02, 0.12, 0.3, 3.3]

model:
    type: 'mobilenet_v3_small'
    pretrained: false

train:
    epochs: 30
    label_smoothing: 0.0
    early_stop_patience: 15
    grad_clip_norm: 2.0
    save_full_checkpt: true
    optimizer:
        name: 'adamw'
        lr: 0.001
        weight_decay: 0.0001
    scheduler:
        name: 'onecycle'
        max_lr: 0.001
        pct_start: 0.05
        div_factor: 20.0
        final_div_factor: 10000.0

kd:
    teacher:
        checkpt: 'runs\\2025-10-26_17-53-08_teacher_mbv3l_vww96\\model.pt'
        arch: 'mobilenet_v3_large'
        pretrained: true
    alpha: 0.6
    alpha_constant: true
    temperature: 2.0
    teacher_input_size: 96
    label_smoothing: 0.0
    confidence_gamma:
    margin_weight: 0.0
