meta:
    name: 'student_mbv3s_vww96'
    seed: 42
    out_dir: 'runs'
    device: 'auto' # auto|cuda|mps|cpu

data:
    path: 'data/vww96'
    batch: 256
    num_workers: 4
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    aug:
        rand_hflip: 0.5
        color_jitter: [0.2, 0.2, 0.2, 0.0] # [b, c, s, h]
        random_erasing: [0.0, 0.02, 0.12, 0.3, 3.3] # [p, scale-, scale+, ratio-, ratio+]

model:
    type: 'mobilenet_v3_small' # mobilenet_v3_small | mobilenet_v3_large
    pretrained: true
    # dropout: 0.0 ?

train:
    epochs: 30
    label_smoothing: 0.05
    early_stop_patience: 6
    grad_clip_norm: 2.0
    optimizer:
        name: 'adamw'
        lr: 0.0005
        weight_decay: 0.0001
    scheduler:
        name: 'onecycle'
        max_lr: 0.0005
        pct_start: 0.3
        div_factor: 10.0
        final_div_factor: 200.0

kd:
    teacher:
        checkpt: 'saved_runs\2025-11-09_15-42-08_teacher_mbv3l_vww96_self_distill\model.pt'
        arch: 'mobilenet_v3_large'
        pretrained: true
    alpha: 0.50
    alpha_constant: false
    alpha_start: 0.40
    alpha_end: 0.50
    alpha_warmup_epochs: 3
    alpha_decay_end_epoch: 12
    temperature: 4.0
    teacher_input_size: 96
    label_smoothing: 0.02
    confidence_gamma: 1.0
    margin_weight: 0.02
    margin_weight_start:
    margin_weight_end:
    margin_weight_decay_end_epoch:
